// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyfcogiygkhptjgfhndc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZmNvZ2l5Z2tocHRqZ2ZobmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTk1MjYsImV4cCI6MjA3NTE3NTUyNn0._6_nhOUnOMTC9SA3ac6s1bOt2oy3WVa6sWvqiXLqXtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});